### ISSUE TITLE
Could we decide on a name?

### ISSUE THREAD

**Issue by steppers** [mattconsto/gamejam#36]
I quite like adrift

**Comment by mattconsto** [comment]
I'm personally a fan of ***INSERT NAME HERE***

**Comment by steppers** [comment]
That really doesn't help me...

**Comment by mattconsto** [comment]
We can't really use [Adrift](https://en.wikipedia.org/wiki/Adrift_%28video_game%29), [Astray](http://www.indiedb.com/games/astray) or [Forgotten](http://gamejolt.com/games/other/forgotten/14188/).

**Comment by jemeson007** [comment]
Tentative Name: "Lost Survivor"
Broadly classifying the considerations:


   - UI improvements / Usability
   - Battle Dynamics / Intensity
   - Acoustics
   - Memory Management / Reliability
   - AI lifestyle - features, (in)capabilities.


On  Human Computer Interaction, I reckon we could add a social engine to
enable 'gaming circles'. It's a whole new world to explore so they can even
build settlements and implement defences. It could be integrated on any of
the social tools like facebook or google hangouts.

Location: the google maps api can power accurate location details, simulate
reality better hence enable more possibilities, since users will be able to
'relate' with it more intuitively.

Finally, we could look to make it a platform (open/closed) to more
developers to build the world as people want.

-Iroakaazy

**Comment by steppers** [comment]
'Deserted', 'The Deserted' or 'Islander'

**Comment by jemeson007** [comment]
The Deserted sound good
